### ISSUE TITLE
Alias Oj::ParserError exception

### ISSUE THREAD

**Issue by GaryBer** [Curatess/easy-jsonapi#45]
You should alias the `Oj::ParserError` exception to something like `JSONAPI::Exceptions::JSONParserError`

This would prevent code changes for users if you ever switch to another JSON parser. 

For decoupling reasons, you should also consider bridging/wrapping `Oj`.

![image](https://user-images.githubusercontent.com/34002641/112531000-0f297f80-8d75-11eb-9263-549e47ae0c78.png)

**Comment by joshdemoss** [comment]
#48 Closes this issue, thanks for the suggestion.
